// Contains the GUI definition for the License Manager dialog.
DIALOG DLG_LICENSE_MANAGER
{
  NAME IDS_LICENSE_MANAGER;
  SCALE_H; SCALE_V;

  // Main group containing all other groups and gadgets.
  GROUP ID_GRP_MAIN
  {
    ALLOW_WEIGHTS;
    BORDERSIZE 8, 8, 8, 8; 
    COLUMNS 2;
    SCALE_H; SCALE_V;
    SPACE 4, 4;
    
    // Tab group containing the different tabs.
    TAB ID_TAB_GROUPS
    {
      SCALE_H; SCALE_V;

      // The "Data" tab.
      GROUP ID_GRP_DATA
      {
        SCALE_H; SCALE_V;
        BORDERSIZE 4, 4, 4, 4; 
        COLUMNS 2;
        NAME IDS_GRP_DATA;
        SPACE 4, 4;

        STATICTEXT { NAME IDS_LBL_DATA_SALT; CENTER_V; ALIGN_LEFT; }
        EDITTEXT ID_EDT_DATA_SALT { SCALE_H; }

        STATICTEXT { NAME IDS_LBL_DATA_FILE_KEY; CENTER_V; ALIGN_LEFT; }
        EDITTEXT ID_EDT_DATA_FILE_KEY { SCALE_H; }

        STATICTEXT { NAME IDS_LBL_DATA_USER_NAME; CENTER_V; ALIGN_LEFT; }
        GROUP
        {
          SCALE_H; COLUMNS 2; 
          SPACE 4, 4;

          EDITTEXT ID_EDT_DATA_USER_NAME { SCALE_H; }
          EDITTEXT ID_EDT_DATA_USER_SURNAME { SCALE_H; }
        }

        STATICTEXT { NAME IDS_LBL_DATA_USER_ID; CENTER_V; ALIGN_LEFT; }
        EDITTEXT ID_EDT_DATA_USER_ID { SCALE_H; }

        STATICTEXT { NAME IDS_LBL_DATA_SYSTEM_ID; CENTER_V; ALIGN_LEFT; }
        EDITTEXT ID_EDT_DATA_SYSTEM_ID { SCALE_H; }

        STATICTEXT { NAME IDS_LBL_DATA_PRODUCT_ID; CENTER_V; ALIGN_LEFT; }
        EDITTEXT ID_EDT_DATA_PRODUCT_ID { SCALE_H; }

        STATICTEXT { NAME IDS_LBL_DATA_PRODUCT_VERSION; CENTER_V; ALIGN_LEFT; }
        EDITTEXT ID_EDT_DATA_PRODUCT_VERSION { SCALE_H; }

        STATICTEXT { NAME IDS_LBL_DATA_ACCOUNT_LICENSES; ALIGN_TOP; ALIGN_LEFT; }
        MULTILINEEDIT ID_EDT_DATA_ACCOUNT_LICENSES { SCALE_H; SCALE_V; SIZE 300, 50; READONLY; }
      }

      // The "License" tab.
      GROUP ID_GRP_LICENSE
      {
        SCALE_H; SCALE_V;
        BORDERSIZE 4, 4, 4, 4; 
        COLUMNS 1;
        NAME IDS_GRP_LICENSE;
        SPACE 4, 4;

        GROUP // The fields in the license tab.
        {
          SCALE_H; SCALE_V;
          COLUMNS 2;
          SPACE 4, 4;

          STATICTEXT { NAME IDS_LBL_LICENSE_TYPE; CENTER_V; ALIGN_LEFT; }
          COMBOBOX ID_CMB_LICENSE_TYPE
          { 
            SCALE_H;

            CHILDS
            {
              ID_CMB_LICENSE_TYPE_COMMERCIAL, IDS_CMB_LICENSE_TYPE_COMMERCIAL;
              ID_CMB_LICENSE_TYPE_DEMO, IDS_CMB_LICENSE_TYPE_DEMO;
              ID_CMB_LICENSE_TYPE_EDUCATIONAL, IDS_CMB_LICENSE_TYPE_EDUCATIONAL;
              ID_CMB_LICENSE_TYPE_NFR, IDS_CMB_LICENSE_TYPE_NFR;
            }
          }

          STATICTEXT { NAME IDS_LBL_LICENSE_STORAGE_MODE; CENTER_V; ALIGN_LEFT; }
          COMBOBOX ID_CMB_LICENSE_STORAGE_MODE
          { 
            SCALE_H;

            CHILDS
            {
              ID_CMB_LICENSE_STORAGE_MODE_FILE, IDS_CMB_LICENSE_STORAGE_MODE_FILE;
              ID_CMB_LICENSE_STORAGE_MODE_SYSTEM, IDS_CMB_LICENSE_STORAGE_MODE_SYSTEM;
            }
          }

          STATICTEXT { NAME IDS_LBL_LICENSE_ACTIVATION_MODE; CENTER_V; ALIGN_LEFT; }
          COMBOBOX ID_CMB_LICENSE_ACTIVATION_MODE 
          { 
            SCALE_H;

            CHILDS
            {
              ID_CMB_LICENSE_ACTIVATION_MODE_RESTART, IDS_CMB_LICENSE_ACTIVATION_MODE_RESTART;
              ID_CMB_LICENSE_ACTIVATION_MODE_NO_RESTART, IDS_CMB_LICENSE_ACTIVATION_MODE_NO_RESTART;
            }
          }

          STATICTEXT { NAME IDS_LBL_LICENSE_USE_SYSTEM_ID; CENTER_V; ALIGN_LEFT; }
          CHECKBOX ID_CHK_LICENSE_USE_SYSTEM_ID { SCALE_H; }

          STATICTEXT { NAME IDS_LBL_LICENSE_USE_PRODUCT_ID; CENTER_V; ALIGN_LEFT; }
          CHECKBOX ID_CHK_LICENSE_USE_PRODUCT_ID { SCALE_H; }

          STATICTEXT { NAME IDS_LBL_LICENSE_KEY; CENTER_V; ALIGN_LEFT; }
          GROUP
          {
            SCALE_H;
            COLUMNS 2;
            SPACE 4, 4;

            EDITTEXT ID_EDT_LICENSE_KEY { SCALE_H; }
            BITMAPBUTTON ID_ICN_LICENSE_KEY_VALID { ICONID1 300000230; }
          }

        }

        GROUP // The buttons in the license tab.
        {
          SCALE_H;
          COLUMNS 4;
          SPACE 4, 4;

          BUTTON ID_BTN_LICENSE_GENERATE { NAME IDS_BTN_LICENSE_GENERATE; ALIGN_LEFT; }
          STATICTEXT { SCALE_H; } // Filler
          BUTTON ID_BTN_LICENSE_ACTIVATE { NAME IDS_BTN_LICENSE_ACTIVATE; ALIGN_RIGHT; }
          BUTTON ID_BTN_LICENSE_DEACTIVATE { NAME IDS_BTN_LICENSE_DEACTIVATE; ALIGN_RIGHT; }
        }
      }
    }

    MULTILINEEDIT ID_EDT_HELP { SCALE_H; SCALE_V; SIZE 0, 0; READONLY; WORDWRAP; }
  }
}